name: Go Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Build 🔨
      continue-on-error: false
      run: go build -v ./...

    - name: Test 🧪
      continue-on-error: false
      run: go test -v ./...
      
    - name: Format
      run: if [ "$(gofmt -s -l ./... | wc -l)" -gt 0 ]; then exit 1; fi
